### ISSUE TITLE
criar script de banco (up e down)

### ISSUE THREAD

**Issue by williansmartins** [williansmartins/impacta-flash-cards#2]
tabela = cartoes

colunas
- idiomaOrigem(varchar 100)
- idiomaDestino(varchar 100)
- textoOrigem(varchar 255)
- textoDestino(varchar 255)
- nivel(inteiro 2)

**Comment by LuisManoel** [comment]
create schema jw;
use jw;
create table 'jw'.'cartoes'(
'ID_CARTOES' INT NOT NULL AUTO_INCREMENT,
'idiomaOrigem' varchar (100) null,
'idiomaOrigem' varchar (100)null ,
'idiomaDestino' varchar (100)null,
'textoOrigem' varchar (255)null,
'textoDestino' varchar (255)null,
primary key ('ID_CARTOES'));

**Comment by LuisManoel** [comment]
-- agora esta certo! 
CREATE TABLE `cartoes` (
  `idcartoes` int(11) NOT NULL AUTO_INCREMENT,
  `idiomaOrigem` varchar(100) DEFAULT NULL,
  `idiomaDestino` varchar(100) DEFAULT NULL,
  `textoOrigem` varchar(255) DEFAULT NULL,
  `textoDestino` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`idcartoes`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by LuisManoel** [comment]
-- agora esta certo!
create schema flashcards;
use flashcards;
CREATE TABLE cartao (
idcartoes int(11) NOT NULL AUTO_INCREMENT,
idiomaOrigem varchar(100) DEFAULT NULL,
idiomaDestino varchar(100) DEFAULT NULL,
textoOrigem varchar(255) DEFAULT NULL,
textoDestino varchar(255) DEFAULT NULL,
PRIMARY KEY (idcartoes)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
